### ISSUE TITLE
能否添加缓存检测功能

### ISSUE THREAD

**Issue by pxw2002** [gogobody/TpCache#12]
缓存插件有木有生效,相信您一定很想知道。开启本项将会在页面的最下方显示缓存信息。注意一般情况下应该关闭本项。仅作测试之用。

**Comment by gogobody** [comment]
看MTTL就知道生没生效了，说明很清楚。

**Comment by JIeJaitt** [comment]
@ppp2020 前台看起来其实不是特别明显，最有效的方法还是查redis库里面有没有key
