### ISSUE TITLE
BUG：实测使用远程redis时报错

### ISSUE THREAD

**Issue by JIeJaitt** [gogobody/TpCache#19]
## 最新1.0.5版本

用的这个方法添加的密码：
```php
$this->redis=$this->redis->auth('密码');
```

```bash
Call to a member function set() on boolError: Call to a member function set() on bool in /var/task/user/usr/plugins/TpCache/driver/typecho_redis.class.php:51
Stack trace:
#0 /var/task/user/usr/plugins/TpCache/Plugin.php(267): typecho_redis->set('/', 'a:2:{s:4:"time"...')
#1 /var/task/user/usr/plugins/TpCache/Plugin.php(255): TpCache_Plugin::setCache(Array)
#2 [internal function]: TpCache_Plugin::S('<!DOCTYPE html>...')
#3 /var/task/user/var/Typecho/Plugin.php(446): call_user_func_array(Array, Array)
#4 /var/task/user/index.php(26): Typecho\Plugin->__call('index.php:end', Array)
#5 {main}
```

**Comment by gogobody** [comment]
just remove `$this->redis=$this->redis->auth('密码');`

try this:
```
$this->redis->auth('密码');
```

**Comment by JIeJaitt** [comment]
@gogobody 没想到大佬这么快就回答了，大佬辛苦。问题已经被解决了；

希望之后的版本能添加上可选添加密码的功能，另外大佬1.0.6beta版本我今天使用的时候，也存在一些问题，但是我忘了，大佬最近有发版Tpcache的计划吗？

**Comment by gogobody** [comment]
> @gogobody 没想到大佬这么快就回答了，大佬辛苦。问题已经被解决了；
> 
> 希望之后的版本能添加上可选添加密码的功能，另外大佬1.0.6beta版本我今天使用的时候，也存在一些问题，但是我忘了，大佬最近有发版Tpcache的计划吗？

是按照上面的方法解决的吗？没啥人用，暂无计划

**Comment by JIeJaitt** [comment]
> > @gogobody 没想到大佬这么快就回答了，大佬辛苦。问题已经被解决了；
> > 希望之后的版本能添加上可选添加密码的功能，另外大佬1.0.6beta版本我今天使用的时候，也存在一些问题，但是我忘了，大佬最近有发版Tpcache的计划吗？
> 
> 是按照上面的方法解决的吗？没啥人用，暂无计划

对，typecho最新版本，php8

哈哈哈，我感觉还是挺多人用的吧，现在typecho重新更新，入坑的人还挺多的

**Comment by JIeJaitt** [comment]
@gogobody 大佬顺便问下，后台的那个是否使用https这里的https是哪个https？有啥用呀

<img width="957" alt="image" src="https://github.com/gogobody/TpCache/assets/77219045/bfb6ae64-6675-478c-a285-3fc293d589fb">
