### ISSUE TITLE
什么时候可以支持1.2.0版本啊

### ISSUE THREAD

**Issue by bluesky0341** [gogobody/TpCache#3]
什么时候可以支持1.2.0版本啊
这个不能用在1.2.0版本啊

**Comment by gogobody** [comment]
什么问题

**Comment by bluesky0341** [comment]
1.2.0版本用不了啊

**Comment by bluesky0341** [comment]
可以启用插件，但是启用了，里面开启缓存，就白屏

**Comment by gogobody** [comment]
测试启动无问题, 1.2 + php8

**Comment by gogobody** [comment]
测试启动 redis 缓存，全局和局部缓存 无问题

**Comment by bluesky0341** [comment]
插件Tpcache的配置信息没有找到

**Comment by gogobody** [comment]
请确认你的插件目录名叫TpCache

**Comment by bluesky0341** [comment]
http://aluminiumnitride.net/index.php/archives/1/

**Comment by bluesky0341** [comment]
开启了redis全局和局部缓存
但是
Database Query Error

**Comment by gogobody** [comment]
cofig.inc.php 加入 
define('__TYPECHO_DEBUG__', true);

开启debug模式

**Comment by bluesky0341** [comment]
加了，还是Database Query Error

**Comment by gogobody** [comment]
没加上或者加错了

**Comment by bluesky0341** [comment]
<?php
// site root path
define('__TYPECHO_ROOT_DIR__', dirname(__FILE__));

// plugin directory (relative path)
define('__TYPECHO_PLUGIN_DIR__', '/usr/plugins');

// theme directory (relative path)
define('__TYPECHO_THEME_DIR__', '/usr/themes');

// admin directory (relative path)
define('__TYPECHO_ADMIN_DIR__', '/admin/');

// register autoload
require_once __TYPECHO_ROOT_DIR__ . '/var/Typecho/Common.php';

// init
\Typecho\Common::init();

// config db
$db = new \Typecho\Db('Pdo_Mysql', 'typecho_');
$db->addServer(array (
  'host' => 'localhost',
  'port' => 3306,
  'user' => 'aluminiu_aluminiumnitride',
  'password' => 'aYmAI7Zrw0',
  'charset' => 'utf8mb4',
  'database' => 'aluminiu_aluminiumnitride',
  'engine' => 'InnoDB',
), \Typecho\Db::READ | \Typecho\Db::WRITE);
\Typecho\Db::set($db);
define('TYPECHO_DEBUG', true);

**Comment by gogobody** [comment]
define('__TYPECHO_DEBUG__', true);
有两个杠，这里被和谐了

**Comment by gogobody** [comment]
__TYPECHO_DEBUG__

**Comment by gogobody** [comment]
T前面和最后G后面，有下划线参考文件里其他

**Comment by bluesky0341** [comment]
现在再帮忙看看
http://aluminiumnitride.net/index.php/archives/1/

**Comment by bluesky0341** [comment]
发布新文章也不行了，显示

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aluminiu_aluminiumnitride.typecho_tepass_posts' doesn't exist

**Comment by gogobody** [comment]
已知问题，稍等会

**Comment by bluesky0341** [comment]
插件禁用后，一切又正常了

**Comment by bluesky0341** [comment]
我的也是php8.0 1.2.0版本

**Comment by bluesky0341** [comment]
不好意思，说错了，刚才我的php版本是7.4，可以启用插件

**Comment by bluesky0341** [comment]
现在换成php8.0，点启用插件，屏幕什么都没有

**Comment by gogobody** [comment]
https://github.com/gogobody/TpCache/archive/refs/heads/main.zip

**Comment by bluesky0341** [comment]
1.2.0版本
php7.4可以启用插件，可以启动 redis 缓存，全局和局部缓存可以，但是发布文章
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aluminiu_aluminiumnitride.typecho_tepass_posts' doesn't exist

1.2.0版本
php8.0 插件无法启动，点启用插件，屏幕什么都没有

**Comment by gogobody** [comment]
更新了上面有地址，不行的话就不知道什么问题了，本地测试同配置无问题。

**Comment by ZiXia1** [comment]
php8.1+typecho开发版照样白屏，调试模式没有任何显示

**Comment by bluesky0341** [comment]
都是用的1.2.0正式版啊

**Comment by gogobody** [comment]
我是1.2 + php 8 无问题，想debug的可以qq联系
