### ISSUE TITLE
获取cookie的dark字段warning

### ISSUE THREAD

**Issue by 0honus0** [gogobody/TpCache#4]
使用handsome主题，cookie里面用的theme_dark字段表示样式，会提示warning信息，已手动修改
希望可以使用别的方法区分

**Comment by gogobody** [comment]
缓存插件只负责缓存，不处理cookie

**Comment by 0honus0** [comment]
// 缓存命中 // 这里是我个人用来控制 主题黑夜模式的...
$html = str_replace('{colorMode}',$_COOKIE['night']=='1'?'dark':'light',$data['html']);

就这一部分

**Comment by gogobody** [comment]
不对主题做适配，因为每个主题处理方式不一样。你可以自行修改适配主题

**Comment by 0honus0** [comment]
好的，只是不确认php是否可以通过 包含字段 而不是一个完整的key值 获取cookie的方式

**Comment by gogobody** [comment]
你可以用 array_key_exist 检查字段是否存在于数组

**Comment by 0honus0** [comment]
好的，感谢
