### ISSUE TITLE
Typech1.2.0，Docker部署的，php测试了7.2、php7.4、php8.0和php8.1，启用插件都出现了白屏

### ISSUE THREAD

**Issue by BaeKey** [gogobody/TpCache#6]
我在前台运行docker，看到报错信息
typecho-nginx-1  | 2022/07/25 15:44:57 [error] 22#22: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class TpCache_Plugin contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Typecho\Plugin\PluginInterface::personalConfig) in /var/www/html/usr/plugins/TpCache/Plugin.php on line 13" while reading response header from upstream

**Comment by gogobody** [comment]
这个插件是在 ty 1.1 的时期开发的

**Comment by BaeKey** [comment]
> 这个插件是在 ty 1.1 的时期开发的

因为我看到被关闭的问题里，1.2是正常可以开启的，然后我在想是不是环境的问题，就换环境测试了一下，然后至于里面提到的修改文件开启debug模式，我不是很清楚那个文件在哪里，我在插件里并没看到cofig.inc.php这个文件

**Comment by gogobody** [comment]
我个人是在服务器测试的1.2没问题
